/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          brown: "#78350f",
          espresso: "#451a03",
          beige: "#f3ede2",
          linen: "#faf7f2",
        },
        inst: {
          bg: "#faf7f2",
          subtle: "#f4eee3",
          sidebar: "#f3ede2",
          panel: "#ffffff",
          hover: "#fdfbf7",
          border: "#e6ded1",
          "border-subtle": "#efe8dc",
          "border-strong": "#d4c8b8",
          ink: "#291e14",
          secondary: "#594a3d",
          muted: "#857465",
          faint: "#b3a496",
          brown: "#78350f",
          "brown-dark": "#451a03",
          "brown-light": "#fef3c7",
          emerald: "#059669",
          "emerald-light": "#ecfdf5",
          "emerald-border": "#a7f3d0",
          rose: "#dc2626",
          "rose-light": "#fef2f2",
          "rose-border": "#fecaca",
          amber: "#d97706",
          "amber-light": "#fffbeb",
          "amber-border": "#fde68a",
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["Cinzel", "serif"],
        mono: [
          '"Plus Jakarta Sans"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
      },
      boxShadow: {
        inst: "0 1px 3px 0 rgba(120, 53, 15, 0.03), 0 1px 2px -1px rgba(120, 53, 15, 0.03)",
        "inst-hover": "0 8px 24px -4px rgba(120, 53, 15, 0.08), 0 2px 6px -1px rgba(120, 53, 15, 0.04)",
        "inst-lg": "0 14px 34px rgba(120, 53, 15, 0.09)",
      },
    },
  },
  plugins: [],
};
