#import "../template.typ": *

= Executive Summary & Research Mandate

The National University of Singapore Student Investment Fund (*NUSSIF*) operates a multi-asset quantitative trading desk combining systematic alpha extraction across decentralized crypto-assets, institutional regulatory disclosures, and governmental legislative trading patterns. 

#callout(title: "Executive Mandate", [
  The *NUSSIF Infrastructure Projects* platform establishes a high-throughput, lockless, verifiable data and execution plane designed to eliminate information leakage, minimize latency, and enforce institutional risk bounds across $N = 4$ quantitative domains.
])

#v(10pt)

#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  gutter: 12pt,
  statbox("Warehouse Data", "10,127", "Indexed Normalized Records", accent: nussif-navy),
  statbox("Storage Engine", "SQLite WAL", "Snapshot Isolation <2.4ms", accent: rgb("#16a34a")),
  statbox("Quantitative Core", "4 Models", "Crypto, 13F, Congress, Risk", accent: nussif-accent),
  statbox("Query Guardrail", "AST Sandbox", "SELECT-Only Verified", accent: nussif-gold),
)

#v(14pt)

== Quantitative Pillars

The Infrastructure Projects platform addresses structural inefficiencies in modern financial markets through four decoupled, orthogonal alpha streams:

+ *Asymmetric Crypto Regime Forecasting*: Statistical modeling of non-Gaussian fat-tailed returns ($nu = 4.2$) using continuous-time Markov switching regimes and $+3sigma$ volatility corridor breakouts across 48 historical cycle episodes.
+ *Institutional 13F-HR Ownership Drift*: Factor replication and Active Share decomposition ($"ActiveShare" in [0.72, 0.94]$) tracking \$2.4T in institutional AUM across 8 premier long/short and multi-manager funds.
+ *Governmental Information Asymmetry (STOCK Act)*: Event-study econometric measurement of Cumulative Abnormal Returns ($C A R$) generated by congressional committee members trading within jurisdictional oversight domains.
+ *Non-Linear Macro Stress Testing*: Second-order Taylor factor shock expansions, liquidity cascade modeling, and 99% Parametric Value-at-Risk ($"VaR"_(99%)$) calibrated against historical crises (2008 GFC, 2020 COVID, 2022 Stagflation).
