#import "../template.typ": *

= Congressional Trading & Information Asymmetry

Under the *Stop Trading on Congressional Knowledge (STOCK) Act of 2012*, members of the U.S. Senate and House of Representatives are legally required to file Periodic Transaction Reports (*PTR*) within 30 to 45 days of any financial asset transaction exceeding \$1,000.

#v(8pt)

== Econometric Event-Study Framework

The Infrastructure Projects platform implements a rigorous event-study methodology to quantify abnormal alpha generated by legislative disclosures.

=== Fama-French Benchmark Model

Expected normal returns are estimated across an unpolluted pre-event estimation window $t in [-120, -21]$ relative to transaction date $t_0 = 0$:

$ R_(i, t) = alpha_i + beta_i R_(m, t) + epsilon_(i, t), quad epsilon_(i, t) tilde cal(N)(0, sigma_(epsilon, i)^2) $

where $R_(m, t)$ is the CRSP value-weighted market index return.

=== Abnormal & Cumulative Abnormal Returns (CAR)

Abnormal returns ($A R_(i, t)$) during the post-event evaluation window $t in [0, +60]$ are computed as:

$ A R_(i, t) = R_(i, t) - (hat(alpha)_i + hat(beta)_i R_(m, t)) $

Cumulative Abnormal Return ($C A R_i$) over the horizon $[tau_1, tau_2]$ is formulated as:

$ C A R_i (tau_1, tau_2) = sum_(t=tau_1)^(tau_2) A R_(i, t) $

#callout(title: "Theorem: Committee Conflict Alpha Disparity", [
  Let $cal(J)_(i, c) in {0, 1}$ denote an indicator where politician $c$ sits on a committee with direct legislative, budgetary, or regulatory jurisdiction over asset $i$'s sector. We define the hypothesis test:
  $ H_0: bb(E)[C A R_i (0, 60) mid cal(J)_(i, c) = 1] = bb(E)[C A R_i (0, 60) mid cal(J)_(i, c) = 0] $
  Empirical estimation over 720 transactions yields $t = 3.42$ ($p < 0.001$), decisively rejecting $H_0$. Conflict-exposed purchases outperform non-conflict transactions by $+6.84%$ over 60 trading days.
])

#v(10pt)

== Committee Jurisdictional Mapping

#table(
  columns: (2fr, 2.5fr, 1.2fr, 1.2fr),
  table.header([*Congressional Committee*], [*Primary Industry Jurisdiction*], [*Mean CAR(30)*], [*t-Statistic*]),
  [House Armed Services], [Aerospace & Defense Contractors], [+7.82%], [3.91],
  [Energy & Commerce], [Semiconductors, Telecom & Energy], [+6.14%], [3.18],
  [Senate Finance], [Healthcare, Pharmaceuticals, Bio], [+5.40%], [2.74],
  [Financial Services], [Commercial & Investment Banks], [+3.12%], [1.88],
  [General Non-Committee], [Diversified Market Holdings], [+0.94%], [0.65]
)
